---
- hosts: backup1
  become: true
  tasks:
  - name: update apt cache
    apt: upgrade=yes update_cache=yes cache_valid_time=86400
  roles:
    - role: backup
    - role: mysql
      db_user_name: "{{ db_user }}"
      db_user_pass: "{{ db_pass }}"
      db_user_host: "%"
