Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  # config.ssh.insert_key = false
  config.vm.define "mysql1" do |mysql1|
    mysql1.vm.box = "ubuntu/trusty64"
    mysql1.vm.network "private_network", ip: "192.168.33.11"
    mysql1.vm.hostname = "mysql1"
    mysql1.ssh.forward_agent = true
    # mysql1.ssh.port = 2222
    mysql1.vm.synced_folder ".", "/vagrant"
    mysql1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    mysql1.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/mysql.yml"
      ansible.inventory_path = "ansible/dev"
    end
  end
end


