Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  # config.ssh.insert_key = false
  config.vm.define "backup1" do |backup1|
    backup1.vm.box = "ubuntu/trusty64"
    backup1.vm.network "private_network", ip: "192.168.33.22"
    backup1.vm.hostname = "backup1"
    backup1.ssh.forward_agent = true
    # backup1.ssh.port = 2223
    backup1.vm.synced_folder ".", "/vagrant"
    backup1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    backup1.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/backup.yml"
      ansible.inventory_path = "ansible/dev"
    end
  end
end


